# Generated by Django 5.2.15 on 2026-06-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('lokasi', models.CharField(max_length=200)),
                ('kegiatan', models.CharField(max_length=200)),
                ('penyerta', models.CharField(max_length=500)),
            ],
        ),
    ]
