# Generated by Django 5.2.15 on 2026-06-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='kategori',
            field=models.CharField(choices=[('luar_gedung', 'Luar Gedung'), ('dalam_gedung', 'Dalam Gedung')], default='luar_gedung', max_length=15),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='penyerta',
            field=models.TextField(),
        ),
    ]
