# Generated by Django 5.2.15 on 2026-06-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HariLibur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('nasional', 'Hari Libur Nasional'), ('cuti_bersama', 'Cuti Bersama'), ('custom', 'Custom')], default='nasional', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='sub_kategori',
            field=models.CharField(blank=True, choices=[('posyandu', 'Posyandu'), ('bok', 'BOK'), ('sekolah', 'Sekolah'), ('kunjungan_lapangan', 'Kunjungan Lapangan'), ('inspeksi', 'Inspeksi Kesehatan'), ('rapat', 'Rapat'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
    ]
