# Generated by Django 5.2.15 on 2026-06-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_harilibur_kegiatan_is_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='source',
            field=models.CharField(choices=[('google_sheet', 'Google Sheet'), ('manual', 'Input Manual'), ('randomize', 'Randomize')], default='manual', max_length=15),
        ),
    ]
